(require-package 'company)
(global-company-mode 1)

(require-package 'eglot)
(require 'eglot)
(add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))
;; (add-to-list 'eglot-server-programs '((c++-mode c-mode) "/opt/homebrew/opt/llvm/bin/clangd"))
(add-to-list 'eglot-stay-out-of 'company)
(add-to-list 'eglot-stay-out-of 'imenu)

(defun my-eglot-common-hook()
  (company-mode t)
  eglot-ensure)
(add-hook 'c-mode-hook 'eglot-ensure)
(add-hook 'c++-mode-hook 'eglot-ensure)
;; (add-hook 'c-mode-hook 'my-eglot-common-hook)
;; (add-hook 'c++-mode-hook 'my-eglot-common-hook)
;; (add-hook 'emacs-lisp-mode-hook 'my-eglot-common-hook)

(provide 'init-eglot)
